# Generated by Django 6.0.2 on 2026-05-21 19:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RehabWeb_API', '0001_create_role_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilClinico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnostico_principal', models.CharField(max_length=180)),
                ('historial_medico', models.TextField(blank=True)),
                ('nivel_movilidad', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('dependiente', 'Dependiente')], default='medio', max_length=20)),
                ('restricciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TerapeutaProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=120)),
                ('numero_licencia', models.CharField(max_length=80, unique=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_terapeuta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PacienteProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('estrategia_validacion', models.CharField(default='Libre', max_length=120)),
                ('estrategia_progreso', models.CharField(default='Por rutinas', max_length=120)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_paciente', to=settings.AUTH_USER_MODEL)),
                ('perfil_clinico', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente', to='RehabWeb_API.perfilclinico')),
                ('terapeuta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='RehabWeb_API.terapeutaprofile')),
            ],
        ),
    ]
